# Generated by Django 3.1.2 on 2022-01-29 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220129_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='workefficiency',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
